# Data frames

Tables as pandas renders them.

In [1]:
import pandas as pd
moons = pd.DataFrame(
    {
        "planet": ["Jupiter", "Jupiter", "Jupiter", "Jupiter", "Saturn", "Neptune"],
        "radius_km": [1821.6, 1560.8, 2634.1, 2410.3, 2574.7, 1353.4],
        "density_g_cm3": [3.528, 3.013, 1.942, 1.834, 1.882, 2.061],
        "orbit_days": [1.769, 3.551, 7.155, 16.689, 15.945, -5.877],
        "discovered": [1610, 1610, 1610, 1610, 1655, 1846],
    },
    index=pd.Index(["Io", "Europa", "Ganymede", "Callisto", "Titan", "Triton"], name="moon"),
)
moons

           planet  radius_km  density_g_cm3  orbit_days  discovered
moon
Io        Jupiter     1821.6          3.528       1.769        1610
Europa    Jupiter     1560.8          3.013       3.551        1610
Ganymede  Jupiter     2634.1          1.942       7.155        1610
Callisto  Jupiter     2410.3          1.834      16.689        1610
Titan      Saturn     2574.7          1.882      15.945        1655
Triton    Neptune     1353.4          2.061      -5.877        1846

In [2]:
moons.describe()

         radius_km  density_g_cm3  orbit_days   discovered
count     6.000000       6.000000    6.000000     6.000000
mean   2059.150000       2.376667    6.538667  1656.833333
std     551.820879       0.715297    8.691523    94.404273
min    1353.400000       1.834000   -5.877000  1610.000000
25%    1626.000000       1.897000    2.214500  1610.000000
50%    2115.950000       2.001500    5.353000  1610.000000
75%    2533.600000       2.775000   13.747500  1643.750000
max    2634.100000       3.528000   16.689000  1846.000000

In [3]:
wide = pd.DataFrame({f'column {i}': [i * j for j in range(4)] for i in range(24)})
wide

,column 0,column 1,column 2,column 3,column 4,column 5,column 6,column 7,column 8,column 9,...,column 14,column 15,column 16,column 17,column 18,column 19,column 20,column 21,column 22,column 23
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
2,0,2,4,6,8,10,12,14,16,18,...,28,30,32,34,36,38,40,42,44,46
3,0,3,6,9,12,15,18,21,24,27,...,42,45,48,51,54,57,60,63,66,69

In [4]:
moons.groupby('planet').agg(['mean', 'max'])

        radius_km         density_g_cm3        orbit_days         discovered  \
             mean     max          mean    max       mean     max       mean
planet
Jupiter    2106.7  2634.1       2.57925  3.528      7.291  16.689     1610.0
Neptune    1353.4  1353.4       2.06100  2.061     -5.877  -5.877     1846.0
Saturn     2574.7  2574.7       1.88200  1.882     15.945  15.945     1655.0


          max
planet
Jupiter  1610
Neptune  1846
Saturn   1655

In [5]:
print(moons.to_string())

           planet  radius_km  density_g_cm3  orbit_days  discovered
moon
Io        Jupiter     1821.6          3.528       1.769        1610
Europa    Jupiter     1560.8          3.013       3.551        1610
Ganymede  Jupiter     2634.1          1.942       7.155        1610
Callisto  Jupiter     2410.3          1.834      16.689        1610
Titan      Saturn     2574.7          1.882      15.945        1655
Triton    Neptune     1353.4          2.061      -5.877        1846